package at.halasi.backend;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class TaskServiceIT extends AbstractPostgresIT {

    @Autowired
    private TaskService taskService;

    @Autowired
    private TaskRepository taskRepository;

    @AfterEach
    void cleanup() {
        // ✅ Prevent test data leaking between tests
        taskRepository.deleteAll();
    }

    @Test
    void createMultipleTasks_andFetchAll_andFetchById() {

        // ✅ 1️⃣ Create multiple tasks via REAL service
        var dto1 = new TaskDTO("Task One", "First description");
        var dto2 = new TaskDTO("Task Two", "Second description");
        var dto3 = new TaskDTO("Task Three", "Third description");

        var t1 = taskService.createTask(dto1);
        var t2 = taskService.createTask(dto2);
        var t3 = taskService.createTask(dto3);

        // ✅ 2️⃣ Verify IDs were generated by REAL Postgres
        assertThat(t1.getId()).isNotNull();
        assertThat(t2.getId()).isNotNull();
        assertThat(t3.getId()).isNotNull();

        // ✅ 3️⃣ Fetch ALL tasks via service
        List<Task> allTasks = taskService.getAllTasks();

        assertThat(allTasks).hasSize(3);
        assertThat(allTasks)
                .extracting(Task::getTitle)
                .containsExactly("Task One", "Task Two", "Task Three");

        // ✅ 4️⃣ Fetch by ID (REAL DB lookup)
        Task fetched = taskService.getTaskById(t2.getId());

        assertThat(fetched).isNotNull();
        assertThat(fetched.getId()).isEqualTo(t2.getId());
        assertThat(fetched.getTitle()).isEqualTo("Task Two");
        assertThat(fetched.getDescription()).isEqualTo("Second description");
        assertThat(fetched.isCompleted()).isFalse();

        // ✅ 5️⃣ Double check DB contents directly (safety net)
        List<Task> fromDb = taskRepository.findAll();
        assertThat(fromDb).hasSize(3);
    }
}
